import {ServiceImplementation, Status} from 'nice-grpc';
import {
  DescriptorProto,
  EnumDescriptorProto,
  FileDescriptorProto,
  FileDescriptorSet,
  MethodDescriptorProto,
  ServiceDescriptorProto,
} from 'google-protobuf/google/protobuf/descriptor_pb';
import {IServerReflectionService} from './proto/grpc/reflection/v1/reflection_grpc_pb';
import {
  ErrorResponse,
  ExtensionNumberResponse,
  FileDescriptorResponse,
  ListServiceResponse,
  ServerReflectionRequest,
  ServerReflectionResponse,
  ServiceResponse,
} from './proto/grpc/reflection/v1/reflection_pb';
import {BinaryReader} from 'google-protobuf';

export {ServerReflectionService} from './proto/grpc/reflection/v1/reflection_grpc_pb';

/**
 * Mode used to generate the encoded `FileDescriptor` values used by the server
 * reflection protocol.
 *
 * More specifically, it controls how the value for
 * `grpc.reflection.v1.FileDescriptorResponse.file_descriptor_proto` is
 * generated.
 *
 * - `"slice"`: Copy slices from the input `protoset` value.
 * - `"subarray"`: Use subarray views into the input `protoset` value.
 *   `protoset` must be immutable to avoid unexpected behavior.
 * - `"encode"`: Decode, then re-encode the input `protoset` value.
 *
 */
export type FdProtoMode = 'slice' | 'subarray' | 'encode';

/**
 * Options for the server reflection service.
 *
 * This objects controls details of the implementation built by the
 * `ServerReflection` function.
 */
export interface ServerReflectionOptions {
  /**
   * Filter specifying the full name of services to expose.
   *
   * This list acts as an allowlist for services to be exposed by the
   * `ListServices` reflection query. An empty list means that no service will
   * be exposed.
   */
  serviceNames: string[];

  /**
   * Mode used to generate encoded `FileDescriptor` values.
   *
   * See `FdProtoMode` for details.
   *
   * - Default: `"slice"`.
   */
  fdProtoMode?: FdProtoMode;
}

/**
 * Deserialization implementation of `google.protobuf.FileDescriptorSet` able
 * to track the source slice for each file.
 *
 * The deserialization logic is based on the protobuf definitions and the code
 * generated in the `google-protobuf` package.
 *
 * For each deserialized file descriptor, the source slice is attached to it
 * in the `fileSource` weakmap. `useSlice` controls whether to use slices
 * (copies) or subarrays (views) for the sources.
 */
function deserializeFileDescriptorSetWithFileSource(
  bytes: Uint8Array,
  fileSource: WeakMap<FileDescriptorProto, Uint8Array>,
  useSlice: boolean,
): FileDescriptorSet {
  const reader = new BinaryReader(bytes);
  const msg = new FileDescriptorSet();
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    const field: number = reader.getFieldNumber();
    switch (field) {
      case 1: {
        const value = new FileDescriptorProto();
        // offset of the message start, null if the reader is never called
        let start: null | number = null;
        reader.readMessage(value, (msg: any, binaryReader: BinaryReader) => {
          if (start === null) {
            start = binaryReader.getCursor();
          }
          return FileDescriptorProto.deserializeBinaryFromReader(
            msg,
            binaryReader,
          );
        });
        const end = reader.getCursor();
        // if the reader is never called (should be impossible), default to the
        // end offset to produce an empty source.
        start = start ?? end;
        msg.addFile(value);
        fileSource.set(
          value,
          useSlice ? bytes.slice(start, end) : bytes.subarray(start, end),
        );
        break;
      }
      default: {
        reader.skipField();
        break;
      }
    }
  }
  return msg;
}

/**
 * Implement the [`grpc.reflection.v1.ServerReflection`](https://github.com/grpc/grpc-proto/blob/master/grpc/reflection/v1/reflection.proto)
 * service for the provided file descriptor set.
 *
 * @param protoset Protobuf-encoded file descriptor set. This is a
 *   protobuf-encoded [google.protobuf.FileDescriptorSet](https://github.com/protocolbuffers/protobuf/blob/89c585602af7d28646ce92cd3abba07cfdad7fa6/src/google/protobuf/descriptor.proto#L56)
 *   value. It is usually generated by the protobuf compiler using the
 *   flag `--descriptor_set_out`. If using the option `fdProtoMode: "slice"`
 *   (default), this value is assumed to be an immutable `Uint8Array` value.
 *   If you can't guarantee immutability, clone the `protoset` value before
 *   passing it to this function (for example, using
 *   `Uint8Array.from(protoset)`).
 * @param options Server reflection implementation options. If you provide a
 *   string array, it is treated as an option object using the provided list for
 *   its `serviceNames` field.
 *
 *   See `ServerReflectionOptions` for details.
 */
export function ServerReflection(
  protoset: Uint8Array,
  options: Readonly<ServerReflectionOptions> | readonly string[],
): ServiceImplementation<IServerReflectionService> {
  const resolvedOptions: Readonly<ServerReflectionOptions> = Array.isArray(
    options,
  )
    ? {serviceNames: options}
    : (options as ServerReflectionOptions);
  const serviceNames: readonly string[] = resolvedOptions.serviceNames;
  const fdProtoMode: FdProtoMode = resolvedOptions.fdProtoMode ?? 'slice';

  // cache from file descriptor values to their protobuf-encoded value
  const fdProtoCache: WeakMap<FileDescriptorProto, Uint8Array> = new WeakMap();
  const fileDescriptorSet =
    fdProtoMode === 'slice' || fdProtoMode === 'subarray'
      ? deserializeFileDescriptorSetWithFileSource(
          protoset,
          fdProtoCache,
          fdProtoMode === 'slice',
        )
      : FileDescriptorSet.deserializeBinary(protoset);

  function getEncodedFileDescriptorProto(
    fileDescriptorProto: FileDescriptorProto,
  ): Uint8Array {
    let encoded: Uint8Array | undefined = fdProtoCache.get(fileDescriptorProto);
    if (encoded === undefined) {
      encoded = fileDescriptorProto.serializeBinary();
      fdProtoCache.set(fileDescriptorProto, encoded);
    }
    return encoded;
  }

  function findSymbol(
    symbol: string,
    descriptor:
      | FileDescriptorProto
      | DescriptorProto
      | EnumDescriptorProto
      | ServiceDescriptorProto
      | MethodDescriptorProto,
    prefix: string = '',
  ):
    | DescriptorProto
    | EnumDescriptorProto
    | ServiceDescriptorProto
    | MethodDescriptorProto
    | undefined {
    if (descriptor instanceof FileDescriptorProto) {
      const packageName = descriptor.getPackage();

      const packagePrefix = packageName == null ? '' : `${packageName}.`;

      return (
        descriptor
          .getMessageTypeList()
          .find(type => findSymbol(symbol, type, packagePrefix)) ||
        descriptor
          .getEnumTypeList()
          .find(type => findSymbol(symbol, type, packagePrefix)) ||
        descriptor
          .getServiceList()
          .find(type => findSymbol(symbol, type, packagePrefix))
      );
    }

    const fullName = prefix + descriptor.getName();

    if (symbol === fullName) {
      return descriptor;
    }

    if (descriptor instanceof DescriptorProto) {
      const messagePrefix = `${fullName}.`;

      return (
        descriptor
          .getNestedTypeList()
          .find(type => findSymbol(symbol, type, messagePrefix)) ||
        descriptor
          .getEnumTypeList()
          .find(type => findSymbol(symbol, type, messagePrefix))
      );
    }

    if (descriptor instanceof ServiceDescriptorProto) {
      const servicePrefix = `${fullName}.`;

      return descriptor
        .getMethodList()
        .find(method => findSymbol(symbol, method, servicePrefix));
    }

    return undefined;
  }

  function handleRequest(
    request: ServerReflectionRequest,
  ): ServerReflectionResponse {
    switch (request.getMessageRequestCase()) {
      case ServerReflectionRequest.MessageRequestCase.FILE_BY_FILENAME: {
        const filename = request.getFileByFilename();

        const fileDescriptorProto = fileDescriptorSet
          .getFileList()
          .find(file => file.getName() === filename);

        if (fileDescriptorProto == null) {
          return new ServerReflectionResponse().setErrorResponse(
            new ErrorResponse()
              .setErrorCode(Status.NOT_FOUND)
              .setErrorMessage(`File not found: ${filename}`),
          );
        }

        return new ServerReflectionResponse()
          .setOriginalRequest(request)
          .setFileDescriptorResponse(
            new FileDescriptorResponse().setFileDescriptorProtoList([
              getEncodedFileDescriptorProto(fileDescriptorProto),
            ]),
          );
      }

      case ServerReflectionRequest.MessageRequestCase.FILE_CONTAINING_SYMBOL: {
        const symbol = request.getFileContainingSymbol();

        const fileDescriptorProto = fileDescriptorSet
          .getFileList()
          .find(file => findSymbol(symbol, file) != null);

        if (fileDescriptorProto == null) {
          return new ServerReflectionResponse().setErrorResponse(
            new ErrorResponse()
              .setErrorCode(Status.NOT_FOUND)
              .setErrorMessage(`Symbol not found: ${symbol}`),
          );
        }

        return new ServerReflectionResponse()
          .setOriginalRequest(request)
          .setFileDescriptorResponse(
            new FileDescriptorResponse().setFileDescriptorProtoList([
              getEncodedFileDescriptorProto(fileDescriptorProto),
            ]),
          );
      }

      case ServerReflectionRequest.MessageRequestCase
        .FILE_CONTAINING_EXTENSION: {
        const extensionRequest = request.getFileContainingExtension()!;
        const containingType = extensionRequest.getContainingType();
        const extensionNumber = extensionRequest.getExtensionNumber();

        const fileDescriptorProto = fileDescriptorSet
          .getFileList()
          .find(file => {
            const descriptor = findSymbol(containingType, file);

            return (
              descriptor instanceof DescriptorProto &&
              descriptor
                .getExtensionList()
                .some(extension => extensionNumber === extension.getNumber())
            );
          });

        if (fileDescriptorProto == null) {
          return new ServerReflectionResponse().setErrorResponse(
            new ErrorResponse()
              .setErrorCode(Status.NOT_FOUND)
              .setErrorMessage(
                `Extension not found: ${containingType}(${extensionNumber})`,
              ),
          );
        }

        return new ServerReflectionResponse()
          .setOriginalRequest(request)
          .setFileDescriptorResponse(
            new FileDescriptorResponse().setFileDescriptorProtoList([
              getEncodedFileDescriptorProto(fileDescriptorProto),
            ]),
          );
      }

      case ServerReflectionRequest.MessageRequestCase.LIST_SERVICES: {
        return new ServerReflectionResponse()
          .setOriginalRequest(request)
          .setListServicesResponse(
            new ListServiceResponse().setServiceList(
              serviceNames.map(serviceName =>
                new ServiceResponse().setName(serviceName),
              ),
            ),
          );
      }

      case ServerReflectionRequest.MessageRequestCase
        .ALL_EXTENSION_NUMBERS_OF_TYPE: {
        const type = request.getAllExtensionNumbersOfType();

        return new ServerReflectionResponse().setAllExtensionNumbersResponse(
          new ExtensionNumberResponse().setBaseTypeName(type),
        );
      }
    }

    return new ServerReflectionResponse().setErrorResponse(
      new ErrorResponse()
        .setErrorCode(Status.UNIMPLEMENTED)
        .setErrorMessage('Not implemented'),
    );
  }

  return {
    async *serverReflectionInfo(
      requests: AsyncIterable<ServerReflectionRequest>,
    ): AsyncIterable<ServerReflectionResponse> {
      for await (const request of requests) {
        yield handleRequest(request);
      }
    },
  };
}
